name: split_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - scikit-learn
  - pip
  - pip:
    - wandb
    - pydantic==2.10.5
    - pydantic-core==2.27.2
    - -e ../../loggers_configuration
