name: post_covid_pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - requests
  - pip
  - mlflow>=2.15.0
  - hydra-core=1.3
  - pip:
    - wandb
    - pydantic==2.10.5
    - pydantic-core==2.27.2
    - -e ../loggers_configuration