name: evaluate_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=25.2
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - matplotlib=3.10.6
  - numpy=2.3.3
  - joblib=1.5.2
  - mlflow=2.20.2
  - pip:
      - wandb
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - -e ../../loggers_configuration